name: Deploy (Pull)
on:
  workflow_run:
    workflows: ["Build & Push Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Debug
        run: |
          pwd
          ls -la
          docker ps -a

      - name: Ensure nginx is running
        run: docker compose up -d nginx

      - name: Detect active
        run: |
          if grep -q "app_blue" nginx.conf; then
            echo "NEW=app_green" >> $GITHUB_ENV
            echo "OLD=app_blue" >> $GITHUB_ENV
          else
            echo "NEW=app_blue" >> $GITHUB_ENV
            echo "OLD=app_green" >> $GITHUB_ENV
          fi

      - name: Pull new image
        run: docker compose pull $NEW

      - name: Start new version
        run: docker compose up -d $NEW

      - name: Debug containers
        run: |
          docker ps -a
          docker logs $NEW || true

      - name: Healthcheck
        run: |
          echo "Waiting for $NEW..."

          for i in {1..20}; do
            if docker exec nginx curl --max-time 2 -s http://$NEW:3000 > /dev/null; then
              echo "App is ready"
              exit 0
            fi
            sleep 2
          done

          echo "App failed"
          docker logs $NEW
          exit 1

      - name: Switch nginx
        run: |
          cat <<EOF > nginx.conf
          server {
              listen 80;

              location / {
                  proxy_pass http://$NEW:3000;
              }
          }
          EOF

          docker exec nginx nginx -t
          docker exec nginx nginx -s reload

      - name: Stop old
        run: docker compose stop $OLD