name: Deploy (Pull)

on:
  workflow_run:
    workflows: ["Build & Push Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Update project
        run: |
          cd /home/nodjs
          git fetch --all
          git reset --hard origin/master

      - name: Detect active
        run: |
          cd /home/nodjs
          if grep -q "app_blue" nginx.conf; then
            echo "NEW=app_green" >> $GITHUB_ENV
            echo "OLD=app_blue" >> $GITHUB_ENV
          else
            echo "NEW=app_blue" >> $GITHUB_ENV
            echo "OLD=app_green" >> $GITHUB_ENV
          fi

      # 🔥 ВАЖНО: теперь НЕ билдим
      - name: Pull new image
        run: |
          cd /home/nodjs
          docker compose pull

      - name: Start new version
        run: |
          cd /home/nodjs
          docker compose up -d $NEW

      - name: Healthcheck
        run: |
          for i in {1..10}; do
            if docker exec nginx curl --max-time 2 -s http://$NEW:3000 > /dev/null; then
              echo "App is ready"
              exit 0
            fi
            sleep 1
          done

          echo "App failed"
          docker logs $NEW
          exit 1

      - name: Switch nginx
        run: |
          cd /home/nodjs

          printf "server {\n\
              listen 80;\n\
              location / {\n\
                  proxy_pass http://$NEW:3000;\n\
              }\n\
          }\n" > nginx.conf

          docker exec nginx nginx -t
          docker exec nginx nginx -s reload

      - name: Stop old
        run: |
          cd /home/nodjs
          docker compose stop $OLD