name: Zero Downtime Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # 👉 Переходим в папку проекта
      - name: Go to project dir
        run: cd /home/nodjs

      # 1. Определяем активный контейнер
      - name: Detect active
        run: |
          cd /home/nodjs
          if grep -q "app_blue" nginx.conf; then
            echo "NEW=app_green" >> $GITHUB_ENV
            echo "OLD=app_blue" >> $GITHUB_ENV
          else
            echo "NEW=app_blue" >> $GITHUB_ENV
            echo "OLD=app_green" >> $GITHUB_ENV
          fi

      # 2. Поднимаем новый контейнер
      - name: Start new version
        run: |
          cd /home/nodjs
          docker compose up -d --build $NEW

      # 3. Ждём (можно потом заменить на healthcheck)
      - name: Wait
        run: sleep 5

      # 4. Переключаем nginx
      - name: Switch nginx
        run: |
          cd /home/nodjs
          sed -i "s/$OLD/$NEW/g" nginx.conf
          docker exec nginx nginx -s reload

      # 5. Останавливаем старый
      - name: Stop old
        run: |
          cd /home/nodjs
          docker compose stop $OLD

      # 6. Чистим мусор
      - name: Cleanup
        run: docker image prune -f
